# 项目相关配置
ruoyi:
  # 名称（TODO 显示在首页等位置，根据项目情况自行更换）
  name: 吉运通用接口平台
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径(/ruoyi/profile 项目部署所在盘符的根本目录； D:/www/ruoyi/profile 也可以配置这样的觉得路径)
  profile: /profile/tysfrz_jsjy/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口 （TODO 根据项目情况自行更换）
  port: 83
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 1000
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

swagger:
  basic:
    enable: false
    username: zhangsan
    password: 123456

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug


# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #jackson
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #profiles
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #redis
  redis:
    enabled: true # Redis开关/默认关闭
    database: 0
    password:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 5000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 1000 # 连接池中的最大空闲连接
        min-idle: 500 # 连接池中的最小空闲连接
        max-wait: 6000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 3000ms
    prefix: tysfrz_jsjy  #前缀（TODO 重要：用于区分不同项目的空间，根据项目情况自行更换）
  session:
    store-type: redis
    redis:
      namespace: tysfrz_jsjy:session
  main:
    allow-bean-definition-overriding: true #遇到相同名字，是否进行覆盖

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ruoyi
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED：忽略 NOT_NULL：非 NULL，默认策略 NOT_EMPTY：非空
      field-strategy: NOT_NULL
      #驼峰下划线转换
      #db-column-underline: true
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      #自定义SQL注入器
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


# 微信公众号配置
wx:
  mp:
    configs:
    - appId: wx2b911f070115b89a #（一个公众号的appid  微驱动）
      secret: a6d343b9592121b3c215c8301b0c3d75 #（公众号的appsecret 微驱动）
      token: 111 #（接口配置里的Token值）
      aesKey: 111 #（接口配置里的EncodingAESKey值）
      webPath: http://hahayu.natapp1.cc
      thirdurl: http://wx.51e.com.cn/get-weixin-code.html
      ##      - appId: 2222 （另一个公众号的appid，以下同上）
#        secret: 1111
#        token: 111
#        aesKey: 111

# restful、jwt配置
api:
  overtime: 15    #接口请求失效时间
  nonceovertime: 15
  basepackage: com.ruoyi.api #restful接口扫描路径
  appsecret: 1q2w3e4r # （TODO token验证用密钥，根据项目情况自行更换）
  token:
    expires: 1 #jwt token过期时间（单位：分钟）
    secretKey: 1q2w3e4r


# 第三方认证配置
auth:
  gitee:
    client-id: 716db1779087e1241dd1f3fec0eb4f88619c146de42b26eb493399e4973137e2
    client-secret: 5a9e0552e6eb2a06758f484ceab49b51d4d7260c58eb9b6c904351d5d6ddd215
    redirect-uri: http://localhost:81/oauth/gitee/login


#
jiyun:
  #shorturl地址
  shortapi:
    url: http://api.t.sina.com.cn/short_url/shorten.json?source=3271760578&url_long=
