# 项目相关配置
ruoyi:
  # 名称（TODO 显示在首页等位置，根据项目情况自行更换）
  name: 吉运Java开发平台3.0
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径(/ruoyi/profile 项目部署所在盘符的根本目录； D:/www/ruoyi/profile 也可以配置这样的觉得路径)
  profile: /profile/tysfrz_jsjy/
  # 获取ip地址开关
  addressEnabled: true
  # dataX插件路径 (项目部署所在盘符的根本目录)
  dataX: C:/java/dataX/bin/

# 开发环境配置
server:
  # 服务端口 （TODO 根据项目情况自行更换）
  port: 81
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 1000
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #jackson
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #profiles
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #redis
  redis:
    enabled: true # Redis开关/默认关闭
    database: 0
    password:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 5000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 1000 # 连接池中的最大空闲连接
        min-idle: 500 # 连接池中的最小空闲连接
        max-wait: 6000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 3000ms
    prefix: tysfrz_jsjy  #前缀（TODO 重要：用于区分不同项目的空间，根据项目情况自行更换）

  main:
      allow-bean-definition-overriding: true #遇到相同名字，是否进行覆盖

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ruoyi
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED：忽略 NOT_NULL：非 NULL，默认策略 NOT_EMPTY：非空
      field-strategy: NOT_NULL
      #驼峰下划线转换
      #db-column-underline: true
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      #自定义SQL注入器
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
    # 不需要拦截的访问
    filterChainDefinitions:
      /favicon.ico** anon
      ,/ruoyi.png** anon
      ,/css/** anon
      ,/docs/** anon
      ,/fonts/** anon
      ,/img/** anon
      ,/ajax/** anon
      ,/js/** anon
      ,/ruoyi/** anon
      ,/druid/** anon
      ,/captcha/captchaImage** anon
      ,/logout logout
      ,/login anon#captchaValidate
      ,/api/** anon
      ,/screen/** anon
      ,/pad/** anon
      ,/wap/** anon
      ,/wx/** anon
      ,/oauth/** anon
      ,/register anon#captchaValidate
      ,/swagger-ui.html anon
      ,/website/** anon

  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 是否将用户在线信息写入数据库
    dbSyncflag: false
    #session保存方式
    store-type: Redis

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen: 
  # 作者
  author: jiyunsoft
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.system
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: biz_

#
jiyun:
  notice:
    mailto: fei.yu@51e.com.cn   #（TODO 用于接收异常通知等信息的邮件地址，根据项目情况自行更换）
    isopen: false #是否开启邮件通知
  websocket:
    url: ws://localhost:81/socketServer #（TODO websocket服务地址，根据项目情况自行更换）
  #shorturl地址
  shortapi:
    url: http://api.t.sina.com.cn/short_url/shorten.json?source=3271760578&url_long=
# 微信公众号配置
wx:
  mp:
    configs:
      - appId: wx2b911f070115b89a #（一个公众号的appid  微驱动）
        secret: a6d343b9592121b3c215c8301b0c3d75 #（公众号的appsecret 微驱动）
        token: 111 #（接口配置里的Token值）
        aesKey: 111 #（接口配置里的EncodingAESKey值）
        webPath: http://hahayu.natapp1.cc
        thirdurl: http://wx.51e.com.cn/get-weixin-code.html
        ##      - appId: 2222 （另一个公众号的appid，以下同上）
#        secret: 1111
#        token: 111
#        aesKey: 111

# restful、jwt配置
api:
  overtime: 15    #接口请求失效时间
  nonceovertime: 15
  basepackage: com.ruoyi.api #restful接口扫描路径
  appsecret: 1q2w3e4r # （TODO token验证用密钥，根据项目情况自行更换）
  token:
    expires: 10 #jwt token过期时间（单位：分钟）

#Actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10111
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always

# 第三方认证配置
auth:
  gitee:
    client-id: 716db1779087e1241dd1f3fec0eb4f88619c146de42b26eb493399e4973137e2
    client-secret: 5a9e0552e6eb2a06758f484ceab49b51d4d7260c58eb9b6c904351d5d6ddd215
    redirect-uri: http://localhost:81/oauth/gitee/login


# 正则表达式(未启用)
#regex:
#  password: ^[a-zA-Z0-9]{6,20}$
#  mobile: ^[1](([3|5|8][\d])|([4][5,6,7,8,9])|([6][5,6])|([7][3,4,5,6,7,8])|([9][8,9]))[\d]{8}$
#  email: ^([a-z0-9A-Z]+[-|\.]?)+[a-z0-9A-Z]@([a-z0-9A-Z]+(-[a-z0-9A-Z]+)?\.)+[a-zA-Z]{2,}$
#  url: http(s)?://([\w-]+\.)+[\w-]+(/[\w- ./?%&=]*)?
#  idcard: (^\d{18}$)|(^\d{15}$)
#  ipaddress: (25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)
#  username: ^[a-zA-Z]\w{5,20}$